import React from 'react';
export const textDetails = () => <div>text distinct</div>;
export const text_detail_0 = (p:any)=> <div>text 0 LLM</div>;
export const text_detail_1 = (p:any)=> <div>text 1 PII scrub</div>;
export const text_detail_2 = (p:any)=> <div>text 2 style transfer</div>;
export const text_detail_3 = (p:any)=> <div>text 3 paraphrase</div>;
export const text_detail_4 = (p:any)=> <div>text 4 LLM</div>;
export const text_detail_5 = (p:any)=> <div>text 5 PII scrub</div>;
export const text_detail_6 = (p:any)=> <div>text 6 style transfer</div>;
export const text_detail_7 = (p:any)=> <div>text 7 paraphrase</div>;
export const text_detail_8 = (p:any)=> <div>text 8 LLM</div>;
export const text_detail_9 = (p:any)=> <div>text 9 PII scrub</div>;
export const text_detail_10 = (p:any)=> <div>text 10 style transfer</div>;
export const text_detail_11 = (p:any)=> <div>text 11 paraphrase</div>;
export const text_detail_12 = (p:any)=> <div>text 12 LLM</div>;
export const text_detail_13 = (p:any)=> <div>text 13 PII scrub</div>;
export const text_detail_14 = (p:any)=> <div>text 14 style transfer</div>;
export const text_detail_15 = (p:any)=> <div>text 15 paraphrase</div>;
export const text_detail_16 = (p:any)=> <div>text 16 LLM</div>;
export const text_detail_17 = (p:any)=> <div>text 17 PII scrub</div>;
export const text_detail_18 = (p:any)=> <div>text 18 style transfer</div>;
export const text_detail_19 = (p:any)=> <div>text 19 paraphrase</div>;