import React from 'react';
export const privacyDetails = () => <div>privacy distinct</div>;
export const privacy_detail_0 = (p:any)=> <div>privacy 0 DP epsilon</div>;
export const privacy_detail_1 = (p:any)=> <div>privacy 1 k-anonymity</div>;
export const privacy_detail_2 = (p:any)=> <div>privacy 2 l-diversity</div>;
export const privacy_detail_3 = (p:any)=> <div>privacy 3 PII</div>;
export const privacy_detail_4 = (p:any)=> <div>privacy 4 DP epsilon</div>;
export const privacy_detail_5 = (p:any)=> <div>privacy 5 k-anonymity</div>;
export const privacy_detail_6 = (p:any)=> <div>privacy 6 l-diversity</div>;
export const privacy_detail_7 = (p:any)=> <div>privacy 7 PII</div>;
export const privacy_detail_8 = (p:any)=> <div>privacy 8 DP epsilon</div>;
export const privacy_detail_9 = (p:any)=> <div>privacy 9 k-anonymity</div>;
export const privacy_detail_10 = (p:any)=> <div>privacy 10 l-diversity</div>;
export const privacy_detail_11 = (p:any)=> <div>privacy 11 PII</div>;
export const privacy_detail_12 = (p:any)=> <div>privacy 12 DP epsilon</div>;
export const privacy_detail_13 = (p:any)=> <div>privacy 13 k-anonymity</div>;
export const privacy_detail_14 = (p:any)=> <div>privacy 14 l-diversity</div>;
export const privacy_detail_15 = (p:any)=> <div>privacy 15 PII</div>;
export const privacy_detail_16 = (p:any)=> <div>privacy 16 DP epsilon</div>;
export const privacy_detail_17 = (p:any)=> <div>privacy 17 k-anonymity</div>;
export const privacy_detail_18 = (p:any)=> <div>privacy 18 l-diversity</div>;
export const privacy_detail_19 = (p:any)=> <div>privacy 19 PII</div>;