import React from 'react';
export const tabularDetails = () => <div>tabular distinct</div>;
export const tabular_detail_0 = (p:any)=> <div>tabular 0 schema</div>;
export const tabular_detail_1 = (p:any)=> <div>tabular 1 constraints</div>;
export const tabular_detail_2 = (p:any)=> <div>tabular 2 relational</div>;
export const tabular_detail_3 = (p:any)=> <div>tabular 3 foreign keys</div>;
export const tabular_detail_4 = (p:any)=> <div>tabular 4 schema</div>;
export const tabular_detail_5 = (p:any)=> <div>tabular 5 constraints</div>;
export const tabular_detail_6 = (p:any)=> <div>tabular 6 relational</div>;
export const tabular_detail_7 = (p:any)=> <div>tabular 7 foreign keys</div>;
export const tabular_detail_8 = (p:any)=> <div>tabular 8 schema</div>;
export const tabular_detail_9 = (p:any)=> <div>tabular 9 constraints</div>;
export const tabular_detail_10 = (p:any)=> <div>tabular 10 relational</div>;
export const tabular_detail_11 = (p:any)=> <div>tabular 11 foreign keys</div>;
export const tabular_detail_12 = (p:any)=> <div>tabular 12 schema</div>;
export const tabular_detail_13 = (p:any)=> <div>tabular 13 constraints</div>;
export const tabular_detail_14 = (p:any)=> <div>tabular 14 relational</div>;
export const tabular_detail_15 = (p:any)=> <div>tabular 15 foreign keys</div>;
export const tabular_detail_16 = (p:any)=> <div>tabular 16 schema</div>;
export const tabular_detail_17 = (p:any)=> <div>tabular 17 constraints</div>;
export const tabular_detail_18 = (p:any)=> <div>tabular 18 relational</div>;
export const tabular_detail_19 = (p:any)=> <div>tabular 19 foreign keys</div>;